[versions]
spring-boot = "4.0.8"
spring-modulith = "2.0.8"
springdoc = "3.0.2"
archunit = "1.5.1"
testcontainers = "2.0.5"
stripe = "34.0.0"
aws-sdk = "2.55.11"
jts = "1.20.0"
jcs = "1.1"
networknt = "3.0.8"
awaitility = "4.3.0"
spotless = "8.10.3"
google-java-format = "1.33.0"

[libraries]
springdoc-webmvc-api = { module = "org.springdoc:springdoc-openapi-starter-webmvc-api", version.ref = "springdoc" }
spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith" }
archunit = { module = "com.tngtech.archunit:archunit-junit5", version.ref = "archunit" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
stripe = { module = "com.stripe:stripe-java", version.ref = "stripe" }
aws-sdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk" }
jts = { module = "org.locationtech.jts:jts-core", version.ref = "jts" }
jcs = { module = "io.github.erdtman:java-json-canonicalization", version.ref = "jcs" }
networknt = { module = "com.networknt:json-schema-validator", version.ref = "networknt" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
